version: "3.8"
services:
  sap-rest-api:
    build: .
    image: hansanders.azurecr.io/sap-rest-api:0.9.2
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
    secrets:
     - sap_password
secrets:
  sap_password:
    file: sap-rest-api.sap.secret
