version: "3.8"
services:
  sap-rest-api:
    build: .
    image: hansanders.azurecr.io/sap-rest-api:0.9.1
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
